require('dotenv').config()
const express = require('express')
const bodyParser = require('body-parser')
const helmet = require('helmet')
const { routes } = require('./lib/routes')
const logger = require('./lib/logger')

logger.init()
const port = process.env.PORT
const app = express()
app.use(helmet())
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
routes(app)
app.listen(port)
